# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'about.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(213, 327)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/按钮图标/图标.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setMaximumSize(QtCore.QSize(91, 91))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/按钮图标/图标.png"))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.github = QtWidgets.QToolButton(Dialog)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/按钮图标/窗体/res/github.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.github.setIcon(icon1)
        self.github.setIconSize(QtCore.QSize(50, 50))
        self.github.setCheckable(False)
        self.github.setAutoRepeat(False)
        self.github.setAutoExclusive(False)
        self.github.setAutoRepeatInterval(100)
        self.github.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.github.setAutoRaise(True)
        self.github.setObjectName("github")
        self.horizontalLayout.addWidget(self.github)
        self.gitee = QtWidgets.QToolButton(Dialog)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/按钮图标/窗体/res/gitee.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.gitee.setIcon(icon2)
        self.gitee.setIconSize(QtCore.QSize(50, 50))
        self.gitee.setAutoRaise(True)
        self.gitee.setObjectName("gitee")
        self.horizontalLayout.addWidget(self.gitee)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(7)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "关于"))
        self.label_2.setText(_translate("Dialog", "版本：v0.2"))
        self.label_3.setText(_translate("Dialog", "PyAutoGUI可视化，主要用于自动操作需要大量重复操作鼠标键盘的软件。"))
        self.github.setText(_translate("Dialog", "github地址"))
        self.gitee.setText(_translate("Dialog", "gitee地址"))
        self.label_4.setText(_translate("Dialog", "[federalsadler@sohu.com] Copyright (c)[2022] "))
import images_rc
